import re
import os
import glob

css_file = "assets/css/inkflow.css"
with open(css_file, "r", encoding="utf-8") as f:
    css_content = f.read()

# Remove comments to avoid false positives
css_content = re.sub(r'/\*.*?\*/', '', css_content, flags=re.DOTALL)

# Find class definitions: .classname followed by anything up to {
# This is much safer than just finding words starting with dot.
class_pattern = re.compile(r'\.([a-zA-Z_-][a-zA-Z0-9_-]*)(?=[^\{]*\{)')
all_classes = set(class_pattern.findall(css_content))

html_files = glob.glob("*.html")
html_contents = ""
for hf in html_files:
    with open(hf, "r", encoding="utf-8") as f:
        html_contents += f.read()

unused_classes = []
# also check if the class is generated by js. inkflow.js might add classes.
js_files = glob.glob("assets/js/*.js")
js_contents = ""
for jf in js_files:
    if os.path.exists(jf):
        with open(jf, "r", encoding="utf-8") as f:
            js_contents += f.read()

for cls in sorted(all_classes):
    if not cls or cls in ['active', 'hover', 'focus']:
        continue
    # Simple text search in HTML and JS contents
    # Search for the exact class name as a word boundary or inside quotes
    if not re.search(r'\b' + re.escape(cls) + r'\b', html_contents) and \
       not re.search(r'\b' + re.escape(cls) + r'\b', js_contents):
        unused_classes.append(cls)

print(f"Total unique classes in CSS: {len(all_classes)}")
print(f"Total unused classes found: {len(unused_classes)}")
print("\nUnused classes:")
for c in unused_classes:
    print(c)
